import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="p-5 bg-neutral-700">Header</header>

				<main className="my-10 p-5">{children}</main>

				<footer className="p-5 bg-slate-700">Footer</footer>
			</body>
		</html>
	);
}
